project:
  type: website
  output-dir: _site
  resources:
    - images/
    - files/

website:
  title: "utku turk"
  site-url: https://www.utkuturk.com


  body-footer: |
    <!-- 100% privacy-first analytics -->
    <script data-collect-dnt="true" async src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
    <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif?collect-dnt=true" alt="" referrerpolicy="no-referrer-when-downgrade"/></noscript>
  comments:
    giscus:
      repo: utkuturk/utkuturk.github.io
      repo-id: "R_kgDOQCZuMw"
      category: "General"
      category-id: "DIC_kwDOQCZuM84CxOt1"
      mapping: title
      reactions-enabled: true
      loading: lazy
      input-position: top
      theme: noborder_light









  navbar:

    pinned: true
    right:

      - text: research
        href: research.qmd
      - text: papers
        href: papers.qmd
      - text: talks
        href: talks.qmd
      - text: teaching
        href: teaching.qmd
      - text: "{{< ai cv >}}"
        href: /files/cv.pdf
        target: "_blank"
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?hl=tr&user=wa7LG9gAAAAJ
        target: "_blank"
      - icon: github
        href: https://github.com/utkuturk
        target: "_blank"
      - icon: twitter
        href: https://twitter.com/UtkuTurkLing
        target: "_blank"
      - icon: bluesky
        href: https://bsky.app/profile/utkuturk.com
        target: "_blank"
format:
  html:
    grid:
      body-width: 800px      # total page content width
      sidebar-width: 260px    # left sidebar
      margin-width: 260px     # right margin ("categories" column)
      gutter-width: 1.5rem    # space between columns
    theme: 
        light: 
          - cosmo 
          - brand
          - theme.scss
        # dark: 
        #   - darkly
        #   - brand
        #   - theme.scss
    css: styles.css
metadata-files:
  - fragments/align-bar.yml